### ISSUE TITLE
Italian translation of "Brackets"

### ISSUE THREAD

**Issue by lecciovich** [brackets-cont/brackets-cont.github.io#18]
Some block are not correctly translated in italian version:
- wrong translation of Brackets in "le staffe"
- not translated visualization of block "made with love and Javascript"
- not translated "Popular extensions" block

<img width="1589" alt="Schermata 2022-01-31 alle 18 33 30" src="https://user-images.githubusercontent.com/22684144/151843718-2cd2c0ff-3efa-4fee-bf21-dbdf54a964bb.png">

<img width="1576" alt="immagine" src="https://user-images.githubusercontent.com/22684144/151844343-4fb64827-5284-458b-96c8-f4d89e536872.png">

**Comment by luke2m** [comment]
Thank you for pointing this out. If you're willing to, we'd love a pull request!

**Comment by abose** [comment]
Addressed in the pull request.
closing. Please reopen if there is anything pending.
