### ISSUE TITLE
Fix sign-in for registry.brackets.io

### ISSUE THREAD

**Issue by idleberg** [brackets-cont/brackets-cont.github.io#30]
As of right now, a sign-in will redirect to https://localhost:3000/auth/github/callback. I'm not sure whether the registry is part of this repository, but it's the closest repository to report this issue. I'm assuming it's a simple problem, e.g. reading the wrong environment variables.

**Comment by abose** [comment]
Apologies for the issue. We are working on a brand new extension manager which is scheduled to be released in a month or two and all extension related workflow is a bit broken right now

**Comment by abose** [comment]
Are you trying to publish or update an extension? Will help with the update if so.

**Comment by idleberg** [comment]
I wanted to update this extension: https://github.com/idleberg/brackets-nsis-mode

**Comment by abose** [comment]
@idleberg Can you attach the exact zip file of the extension that needs to be updated. I will update the registry.

**Comment by idleberg** [comment]
Here you go: [idleberg.nsis-mode-0.10.0.zip](https://github.com/brackets-cont/brackets-cont.github.io/files/8986746/idleberg.nsis-mode-0.10.0.zip)

Thank you!

**Comment by abose** [comment]
Closing as fixed.
@idleberg Please reopen if there are any issues.

Best,
Arun

**Comment by idleberg** [comment]
Sorry for the late reply. How can I confirm it worked? The extensions website still lists v0.9.0, but I haven’t been able yet to check in Brackets.
