### ISSUE TITLE
About translation in portuguese

### ISSUE THREAD

**Issue by christyanbrayan** [brackets-cont/brackets-cont.github.io#34]
Hello, there are some errors in the Portuguese translation and others that I think can be improved. But, I don't quite understand how I can solve this. Is it just editing the `translation.json` file in the pt-BR folder?

**Comment by abose** [comment]
Hi @christyanbrayan 
Yes, you are correct, 
1. Edit https://github.com/brackets-cont/brackets-cont.github.io/blob/gh-pages/locales/pt-BR/translation.json with the translations.
2. change this line to `pt-br` https://github.com/brackets-cont/brackets-cont.github.io/blob/gh-pages/js/load.i18next.js#L11 to test it.
3. If you change any translation while testing, you will have to clear the site data in dev tools to load the new translations 
![image](https://user-images.githubusercontent.com/5336369/212912804-4e1c5d2a-6617-4821-84af-c30655f350ef.png)

**Comment by christyanbrayan** [comment]
Understand, thanks!

**Comment by christyanbrayan** [comment]
@abose I have a question about the step 5 - Update the JSON's `_last.translated`. The last commit is the last commit that changed this file that I'm editing?

Sorry for this again, english is not my first language.
